# Generated by Django 5.0.6 on 2025-08-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_player_shown'),
        ('auction', '0003_player_delete_players'),
    ]

    operations = [
    ]
